// <auto-generated />
using System;
using BookingEventos.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingEventos.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260208192006_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BartenderTipoCoptel", b =>
                {
                    b.Property<Guid>("BartenderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CoptelesId")
                        .HasColumnType("char(36)");

                    b.HasKey("BartenderId", "CoptelesId");

                    b.HasIndex("CoptelesId");

                    b.ToTable("BartenderCopteles", (string)null);
                });

            modelBuilder.Entity("BookingEventos.Domain.Entities.Bartender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreArtistico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioPorHora")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Bartenders");
                });

            modelBuilder.Entity("BookingEventos.Domain.Entities.Dj", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreArtistico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioPorHora")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Djs");
                });

            modelBuilder.Entity("BookingEventos.Domain.Entities.GeneroMusical", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GeneroMusicales");
                });

            modelBuilder.Entity("BookingEventos.Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("BartenderFin")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("BartenderId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("BartenderInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CantidadInvitados")
                        .HasColumnType("int");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DjFin")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DjId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DjInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SalonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("BookingEventos.Domain.Entities.Salon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioPorHora")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Salones");
                });

            modelBuilder.Entity("BookingEventos.Domain.Entities.TipoCoptel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TipoCopteles");
                });

            modelBuilder.Entity("BookingEventos.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DjGeneroMusical", b =>
                {
                    b.Property<Guid>("DjId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GenerosId")
                        .HasColumnType("char(36)");

                    b.HasKey("DjId", "GenerosId");

                    b.HasIndex("GenerosId");

                    b.ToTable("DjGeneros", (string)null);
                });

            modelBuilder.Entity("BartenderTipoCoptel", b =>
                {
                    b.HasOne("BookingEventos.Domain.Entities.Bartender", null)
                        .WithMany()
                        .HasForeignKey("BartenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingEventos.Domain.Entities.TipoCoptel", null)
                        .WithMany()
                        .HasForeignKey("CoptelesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DjGeneroMusical", b =>
                {
                    b.HasOne("BookingEventos.Domain.Entities.Dj", null)
                        .WithMany()
                        .HasForeignKey("DjId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingEventos.Domain.Entities.GeneroMusical", null)
                        .WithMany()
                        .HasForeignKey("GenerosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
